insert into public.workers (
  full_name,
  photo_url,
  region,
  city,
  whatsapp_number,
  skills,
  desired_income,
  income_type,
  availability,
  available_now,
  work_style,
  work_style_note,
  job_duration_preference,
  duration_note,
  short_intro,
  experience,
  show_up_count,
  completed_jobs_count,
  hired_count,
  hire_rate,
  rating_average,
  rating_count
)
select *
from (
  values
  (
    'Mariela Santos',
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80',
    'Distrito Nacional',
    'Santo Domingo',
    '+18090000001',
    array['Limpieza', 'Cocina', 'Hogar'],
    1800::numeric,
    'daily'::public.income_type,
    array['Hoy', 'Mañanas', 'Fines de semana'],
    true,
    'structured'::public.work_style,
    'Me va mejor cuando el trabajo está claro desde el inicio.',
    'Por día o fijo semanal',
    'Puede empezar hoy si confirma temprano.',
    'Soy responsable, llego temprano y puedo empezar hoy.',
    '5 años en casas y apartamentos.',
    42,
    38,
    19,
    76::numeric,
    4.9::numeric,
    21
  ),
  (
    'Joel Ramírez',
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    'Santiago',
    'Santiago',
    '+18090000002',
    array['Construcción', 'Pintura', 'Ayudante'],
    2200::numeric,
    'daily'::public.income_type,
    array['Hoy', 'Semana completa'],
    true,
    'hands_on'::public.work_style,
    'Prefiero resolver con las manos y ver avance rápido.',
    '1 semana o más',
    'Disponible para obra corta o larga.',
    'Trabajo bien, aprendo rápido y me gusta cumplir.',
    'Obras residenciales y pintura interior.',
    31,
    29,
    14,
    70::numeric,
    4.8::numeric,
    16
  ),
  (
    'Ana Peralta',
    'https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?auto=format&fit=crop&w=600&q=80',
    'La Altagracia',
    'Higüey',
    '+18090000003',
    array['Ventas', 'Caja', 'Atención al cliente'],
    18500::numeric,
    'monthly'::public.income_type,
    array['Tardes', 'Noches', 'Fines de semana'],
    false,
    'people_oriented'::public.work_style,
    'Me siento efectiva hablando con clientes y ayudando.',
    'Fijo mensual',
    'Puede iniciar en 3 días.',
    'Me gusta atender bien a la gente y resolver sin dar vueltas.',
    'Tiendas, colmados y caja.',
    18,
    15,
    7,
    58::numeric,
    4.7::numeric,
    9
  ),
  (
    'Luis Miguel Peña',
    'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80',
    'Distrito Nacional',
    'Santo Domingo',
    '+18090000004',
    array['Delivery', 'Mensajería', 'Compras'],
    1500::numeric,
    'daily'::public.income_type,
    array['Hoy', 'Tardes', 'Noches'],
    true,
    'fast_paced'::public.work_style,
    'Me va bien cuando hay movimiento y hay que resolver rápido.',
    'Por día o por semana',
    'Tiene motor propio.',
    'Soy rápido, respondo el teléfono y conozco bien la ciudad.',
    'Delivery, diligencias y rutas urbanas.',
    24,
    21,
    11,
    69::numeric,
    4.8::numeric,
    13
  ),
  (
    'Rosa Méndez',
    'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=600&q=80',
    'Santiago',
    'Santiago',
    '+18090000005',
    array['Cocina', 'Fritura', 'Ayudante de cocina'],
    2000::numeric,
    'daily'::public.income_type,
    array['Mañanas', 'Fines de semana'],
    true,
    'hands_on'::public.work_style,
    'Me gusta trabajar de pie, cocinar y mantener todo limpio.',
    'Por día o fijo semanal',
    'Disponible para cafeterías y comedores.',
    'Cocino con sazón, mantengo mi área limpia y llego temprano.',
    'Comedores, frituras y cocina de casa.',
    29,
    25,
    13,
    72::numeric,
    4.9::numeric,
    18
  ),
  (
    'Carlos Alberto Díaz',
    'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80',
    'La Altagracia',
    'Higüey',
    '+18090000006',
    array['Construcción', 'Carga', 'Ayudante'],
    2100::numeric,
    'daily'::public.income_type,
    array['Hoy', 'Semana completa'],
    true,
    'hands_on'::public.work_style,
    'Trabajo mejor cuando puedo moverme y ver avance.',
    '1 semana o más',
    'Puede trabajar en obra o mantenimiento.',
    'Soy fuerte, serio y no falto cuando confirmo.',
    'Obras pequeñas, carga y apoyo general.',
    22,
    19,
    8,
    62::numeric,
    4.6::numeric,
    11
  ),
  (
    'Yudelka Jiménez',
    'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=600&q=80',
    'Distrito Nacional',
    'Santo Domingo',
    '+18090000007',
    array['Ventas', 'Promoción', 'Atención al cliente'],
    1200::numeric,
    'daily'::public.income_type,
    array['Hoy', 'Tardes', 'Fines de semana'],
    true,
    'people_oriented'::public.work_style,
    'Se me da fácil hablar con la gente y vender.',
    'Por día o campaña corta',
    'Disponible para activaciones y tiendas.',
    'Hablo claro, trato bien al cliente y me gusta vender.',
    'Promociones, tiendas y ventas de calle.',
    17,
    14,
    6,
    55::numeric,
    4.7::numeric,
    8
  ),
  (
    'José Manuel Cruz',
    'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    'Santiago',
    'Santiago',
    '+18090000008',
    array['Delivery', 'Almacén', 'Inventario'],
    1750::numeric,
    'daily'::public.income_type,
    array['Mañanas', 'Tardes'],
    false,
    'structured'::public.work_style,
    'Me gusta saber la ruta y cumplirla bien.',
    'Por semana o mensual',
    'Puede iniciar mañana.',
    'Soy ordenado, cuido los paquetes y confirmo cada entrega.',
    'Almacén, rutas y apoyo de inventario.',
    20,
    17,
    9,
    64::numeric,
    4.8::numeric,
    10
  ),
  (
    'Claudia Núñez',
    'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=600&q=80',
    'La Altagracia',
    'Higüey',
    '+18090000009',
    array['Limpieza', 'Hotel', 'Lavandería'],
    1700::numeric,
    'daily'::public.income_type,
    array['Hoy', 'Mañanas'],
    true,
    'detail_oriented'::public.work_style,
    'Me gusta dejar todo limpio y bien revisado.',
    'Por día o fijo semanal',
    'Disponible para villas, hoteles y casas.',
    'Soy cuidadosa con los detalles y trabajo sin perder tiempo.',
    'Limpieza de habitaciones, villas y lavandería.',
    27,
    24,
    12,
    75::numeric,
    4.9::numeric,
    15
  ),
  (
    'Miguel Ángel Vargas',
    'https://images.unsplash.com/photo-1522556189639-b150ed9c4330?auto=format&fit=crop&w=600&q=80',
    'Distrito Nacional',
    'Santo Domingo',
    '+18090000010',
    array['Cocina', 'Parrilla', 'Ayudante'],
    2300::numeric,
    'daily'::public.income_type,
    array['Noches', 'Fines de semana'],
    false,
    'creative'::public.work_style,
    'Me gusta cocinar, probar sazón y sacar platos buenos.',
    'Por evento o por semana',
    'Disponible para eventos y restaurantes.',
    'Cocino con buen ritmo, soy limpio y trabajo bien bajo presión.',
    'Parrilla, eventos y cocina caliente.',
    16,
    13,
    5,
    50::numeric,
    4.6::numeric,
    7
  )
) as seed (
  full_name,
  photo_url,
  region,
  city,
  whatsapp_number,
  skills,
  desired_income,
  income_type,
  availability,
  available_now,
  work_style,
  work_style_note,
  job_duration_preference,
  duration_note,
  short_intro,
  experience,
  show_up_count,
  completed_jobs_count,
  hired_count,
  hire_rate,
  rating_average,
  rating_count
)
where not exists (
  select 1
  from public.workers
  where workers.whatsapp_number = seed.whatsapp_number
);
